### ISSUE TITLE
Reaper crashes when loading saved presets for gunshof

### ISSUE THREAD

**Issue by vssasks** [soerenbnoergaard/gunshot#1]
Cool plugins, but reaper crashes when loading saved presets for gunshot? Can you fix? Would be also cool to have selection window and knobs on the same tab.

**Comment by soerenbnoergaard** [comment]
Thanks. I must admit that I am not maintaining this plugin anymore, as it seemed to be pushing the DPF framework a bit too far - I believe there was some work going on to improve the limitations I ran into, but I have since found other alternatives that work better to me.

I have switched to Reaper myself, and now use ReaVerb to load impulse responses. Using the Save As dialog, you can select to automatically copy impulse responses into the session folder, so they do not get lost. This method has some advantages in loading speed over my solution. I would recommend you go that route as well.

But thanks for checking out the plugin!
